name: Deploy Next.js App

on:
  push: 
    branches: [CI/CD-DEPLOY]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # FIX: npm ci → npm install --legacy-peer-deps
    - name: Install dependencies (ignore peer conflicts)
      run: npm install --legacy-peer-deps

    - name: Build project (SSR)
      run: npm run build

    - name: Zip build folder
      run: |
        zip -r build.zip .next public package.json next.config.js

    - name: Upload build to server
      uses: appleboy/scp-action@master
      with:
        host: 138.68.84.10
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY_LIVE_SWA }}
        source: "build.zip"
        target: "/tmp/build.zip"

    - name: SSH and run deploy.sh
      uses: appleboy/ssh-action@master
      with:
        host: 138.68.84.10
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY_LIVE_SWA }}
        script: |
          chmod +x /opt/projects/auto_deploy/deploy.sh
          /opt/projects/auto_deploy/deploy.sh app-swadiamonds
